# Generated by Django 5.1.2 on 2024-11-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customuser_role_customuser_tax_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('warranty_status', models.CharField(blank=True, max_length=50, null=True)),
                ('distributor_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
