# Generated by Django 5.1.2 on 2024-11-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('product_manager', 'Product Manager'), ('sales_manager', 'Sales Manager')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
