# Generated by Django 5.1.3 on 2025-01-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_invoice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            preserve_default=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
