# Generated by Django 5.1.4 on 2025-01-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_price_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_refunded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
