# Generated by Django 5.1.3 on 2024-12-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='discount_total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
