# Generated by Django 5.1.2 on 2024-11-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_orderhistory_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='orders',
            field=models.ManyToManyField(related_name='order_histories', to='store.order'),
        ),
    ]
