# Generated by Django 5.1.2 on 2024-11-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orderhistory_total_amount_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10, null=True),
        ),
    ]
