# Generated by Django 5.1.3 on 2024-11-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='added_date',
            new_name='date_added',
        ),
    ]
