# Generated by Django 5.1.3 on 2024-11-24 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_added_date_wishlist_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='date_added',
            new_name='added_date',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='store.product'),
        ),
    ]
